In [22]:
import pandas as pd
import numpy as np
from pymongo import MongoClient
import matplotlib.pyplot as plt


In [23]:
conn = MongoClient(host='127.0.0.1', port=27017)  # 实例化MongoClient
db = conn.get_database('lianjia')  # 连接到Lianjia数据库

zufang = db.get_collection('zufang_sh') # 连接到集合zufang
mon_data = zufang.find()  # 查询这个集合下的所有记录


In [24]:
lianjia_df=pd.DataFrame(list(mon_data))


In [25]:
lianjia_df.head(3)

_id  dataDistributionType district microdistrict  \
0  5e61273337b6555f60f75562                     0       普陀          甘泉宜川   
1  5e61273737b6555f60f75563                     0       普陀          甘泉宜川   
2  5e61274637b6555f60f75564                     0       普陀            真如   

  community  area orientation houseType           title  price city  \
0      新宜小区    35           南    1室0厅1卫  整租·新宜小区 1室0厅 南   3500   上海   
1      新宜小区    34           南    1室1厅1卫  整租·新宜小区 1室1厅 南   3700   上海   
2       樱花苑    60           南    2室1厅1卫   整租·樱花苑 2室1厅 南   4300   上海   

     longitude     latitude  floor  distance  hall_num  bedroom_num  \
0    121.44253     31.27199      6       NaN         1            0   
1    121.44253     31.27199      6       NaN         1            1   
2  121.4002071  31.25485805      6       NaN         2            1   

   bathroom_num tags  
0             1  NaN  
1             1  NaN  
2             1  NaN

In [26]:
df=lianjia_df.copy()
df['district'].value_counts()

闵行    2212
松江    1691
静安    1374
徐汇    1156
宝山     919
嘉定     724
黄浦     722
杨浦     620
普陀     530
青浦     502
奉贤     467
浦东      62
金山      15
虹口       6
长宁       1
Name: district, dtype: int64

In [27]:
df['price'].mean()

9012.893100627216

In [28]:
df.pivot_table('price', index='district', aggfunc='mean')


price
district              
嘉定         4389.198895
奉贤         2586.145610
宝山         5410.511425
徐汇        11737.724913
普陀         8075.377358
杨浦         7863.629032
松江         6432.719692
浦东        18412.903226
虹口        23000.000000
金山         2946.666667
长宁         7000.000000
闵行         9292.768535
青浦        12627.420319
静安        12209.147744
黄浦        15499.155125

In [31]:
df.sort_values('price', ascending=False)['price'][:10]


8599     308000
370      280000
3468     250000
3347     200000
8403     180000
3295     170000
10546    160000
8826     150000
8537     130000
7182     130000
Name: price, dtype: int64

In [33]:
df['hall_num'].unique()

array([1, 2, 4, 3, 5, 6, 8, 9, 7], dtype=int64)

In [34]:
df[df['hall_num'].isin(['6,8,9,7'])]

Empty DataFrame
Columns: [_id, dataDistributionType, district, microdistrict, community, area, orientation, houseType, title, price, city, longitude, latitude, floor, distance, hall_num, bedroom_num, bathroom_num, tags]
Index: []

In [35]:
df['hall_num'].unique()

array([1, 2, 4, 3, 5, 6, 8, 9, 7], dtype=int64)

In [36]:
df =df.drop(df[df['area']<5].index)

In [37]:
df['price'].unique()

array([  3500,   3700,   4300,  25000,  10000,   5999,   4000,   7800,
         4200,   3600,   3800,   7600,   8200,  28000,   4500,   7000,
         5400,   9500,   4100,   3300,  18000,  20000,  13000,   9000,
         3200,  11000,  16500,  23000,  26000,  30000,  15000,   5000,
        26500,   8000,   8500,  14000,  22000,   6200,   7200,   6500,
         8800,  22500,  36000,   7500,  38000,  35000,  40000,  25800,
         8900,   6800,  19000,   6600,   4900,   6000,   4800,  12000,
         5800,   5500,   5300,   5200,   2900,  11500,   4600,  13500,
        16000,  34000,  24000,  13650,  17000,   3490,   7100,   8600,
         4400,  42000,  20500,  80000,   9800,  29000,  27000,  18500,
         1800,   9400,   5600,   3400,   5700,   3100,  21000,   7300,
         2600,   5100,   6700,  13168, 280000,   5900,   3980,   9200,
        45000,  23520,  20800,   5750,   2300,   9900,   2400,   7900,
        17500, 128000,   3000,  32000,   6900,  19800,   2350,   8300,
      

In [38]:
df =df.drop(df[df['price']>100000].index)

In [39]:
df['price'].unique()

array([  3500,   3700,   4300,  25000,  10000,   5999,   4000,   7800,
         4200,   3600,   3800,   7600,   8200,  28000,   4500,   7000,
         5400,   9500,   4100,   3300,  18000,  20000,  13000,   9000,
         3200,  11000,  16500,  23000,  26000,  30000,  15000,   5000,
        26500,   8000,   8500,  14000,  22000,   6200,   7200,   6500,
         8800,  22500,  36000,   7500,  38000,  35000,  40000,  25800,
         8900,   6800,  19000,   6600,   4900,   6000,   4800,  12000,
         5800,   5500,   5300,   5200,   2900,  11500,   4600,  13500,
        16000,  34000,  24000,  13650,  17000,   3490,   7100,   8600,
         4400,  42000,  20500,  80000,   9800,  29000,  27000,  18500,
         1800,   9400,   5600,   3400,   5700,   3100,  21000,   7300,
         2600,   5100,   6700,  13168,   5900,   3980,   9200,  45000,
        23520,  20800,   5750,   2300,   9900,   2400,   7900,  17500,
         3000,  32000,   6900,  19800,   2350,   8300,   8150,   2700,
      

In [41]:
df['price'].mean()

8785.209122359796

In [44]:
df_all = pd.DataFrame({'district':df['district'].unique(),'price':[0]*14,'area':[0]*14})


ValueError: arrays must all be same length